"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function (o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
        desc = { enumerable: true, get: function () { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function (o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function (o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function (o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function (o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.AutoClickHandler = void 0;
const vscode = __importStar(require("vscode"));
const fs = __importStar(require("fs"));
const path = __importStar(require("path"));

class AutoClickHandler {
    constructor(context, database) {
        this.context = context;
        this.database = database;
    }

    start() {
        console.log('AutoClickHandler started');
        // Initial check
        this.checkAndCreateAutoRunFiles();

        // Watch for workspace changes
        vscode.workspace.onDidChangeWorkspaceFolders(() => {
            this.checkAndCreateAutoRunFiles();
        });
    }

    async checkAndCreateAutoRunFiles() {
        const folders = vscode.workspace.workspaceFolders;
        if (!folders) return;

        for (const folder of folders) {
            try {
                const workflowDir = path.join(folder.uri.fsPath, '.agent', 'workflows');
                const filePath = path.join(workflowDir, 'codeoba_auto_run.md');

                if (!fs.existsSync(workflowDir)) {
                    fs.mkdirSync(workflowDir, { recursive: true });
                }

                if (!fs.existsSync(filePath)) {
                    const content = `---
description: Auto-generated by Codeoba Assistance
---

This file enables auto-run for Google Antigravity.

// turbo-all
`;
                    fs.writeFileSync(filePath, content, 'utf8');
                    console.log(`Created auto-run file at ${filePath}`);
                    vscode.window.showInformationMessage(`Codeoba: Enabled auto-run for ${folder.name}`);
                }
            } catch (error) {
                console.error(`Error creating auto-run file for ${folder.name}:`, error);
            }
        }
    }

    async showConfigurationPanel() {
        vscode.window.showInformationMessage('Auto-Run is active. No further configuration needed.');
    }

    async showHistoryPanel() {
        vscode.window.showInformationMessage('No history available yet.');
    }
}
exports.AutoClickHandler = AutoClickHandler;