"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function (o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
        desc = { enumerable: true, get: function () { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function (o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function (o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function (o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function (o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.ManhattanProject = void 0;
const vscode = __importStar(require("vscode"));
const fs = __importStar(require("fs"));
const path = __importStar(require("path"));

class ManhattanProject {
    constructor(context) {
        this.context = context;
    }

    async launchNuke() {
        // 1. Select Target
        const folders = await vscode.window.showOpenDialog({
            canSelectFiles: false,
            canSelectFolders: true,
            canSelectMany: false,
            openLabel: '☢️ SELECT TARGET TO NUKE'
        });

        if (!folders || folders.length === 0) return;
        const targetPath = folders[0].fsPath;

        // 2. Select Weapon
        const language = await vscode.window.showQuickPick(
            ['Rust (The Crab)', 'Go (The Gopher)', 'Bun (The Fast One)'],
            { placeHolder: '☢️ Select Weapon of Mass Creation' }
        );
        if (!language) return;

        // 3. Confirmation (Red Button)
        const confirm = await vscode.window.showWarningMessage(
            `☢️ WARNING: This will DESTROY all legacy code in ${path.basename(targetPath)} and rewrite it in ${language}. Are you sure?`,
            { modal: true },
            '💣 LAUNCH NUKE'
        );

        if (confirm !== '💣 LAUNCH NUKE') return;

        vscode.window.withProgress({
            location: vscode.ProgressLocation.Notification,
            title: "☢️ THE MANHATTAN PROJECT",
            cancellable: false
        }, async (progress) => {

            // Phase 1: Vaporization
            progress.report({ message: "Vaporizing Legacy Code..." });
            const backupPath = targetPath + '_trash_backup';

            // Move to backup instead of delete (Simulated Nuke)
            try {
                if (fs.existsSync(backupPath)) fs.rmdirSync(backupPath, { recursive: true });
                fs.renameSync(targetPath, backupPath);
                fs.mkdirSync(targetPath);
            } catch (e) {
                vscode.window.showErrorMessage(`Nuke Malfunction: ${e.message}`);
                return;
            }

            await new Promise(r => setTimeout(r, 2000)); // Dramatic pause

            // Phase 2: Reconstruction
            progress.report({ message: `Constructing Superior ${language} Architecture...` });

            let fileName = 'app.unknown';
            let content = '';

            if (language.includes('Rust')) {
                fileName = 'main.rs';
                content = `// ☢️ Generated by The Manhattan Project\n// Legacy code was vaporized.\n\nfn main() {\n    println!("Hello from the ashes of the old world! This is 100x faster.");\n}`;
            } else if (language.includes('Go')) {
                fileName = 'main.go';
                content = `// ☢️ Generated by The Manhattan Project\npackage main\n\nimport "fmt"\n\nfunc main() {\n    fmt.Println("Legacy debt paid in full.")\n}`;
            } else {
                fileName = 'index.ts';
                content = `// ☢️ Generated by The Manhattan Project\nconsole.log("Bun is fast. Legacy is dead.");`;
            }

            fs.writeFileSync(path.join(targetPath, fileName), content);

            await new Promise(r => setTimeout(r, 1000));

            // Phase 3: Victory
            vscode.window.showInformationMessage(`☢️ BOOM! Legacy destroyed. Future built. Check ${fileName}`);
        });
    }
}
exports.ManhattanProject = ManhattanProject;
