"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VoiceCommander = void 0;
const vscode = require("vscode");

class VoiceCommander {
    constructor(context) {
        this.context = context;
    }

    async listen() {
        // Simulate Voice Interface via Input Box (Text-to-Action)
        const command = await vscode.window.showInputBox({
            prompt: '🎙️ Codeoba Voice Command (Type usage instructions)',
            placeHolder: 'e.g., "Create a new React component called Header"',
            title: 'Listening...'
        });

        if (command) {
            this.processNaturalLanguage(command);
        }
    }


    async processNaturalLanguage(input) {
        const lower = input.toLowerCase();

        if (lower.includes('create') && lower.includes('component')) {
            vscode.commands.executeCommand('codeoba.manageTemplates');
        } else if (lower.includes('switch') && lower.includes('account')) {
            vscode.commands.executeCommand('codeoba.switchAccount');
        } else if (lower.includes('fix')) {
            vscode.commands.executeCommand('codeoba.fixLastError');
        } else if (lower.includes('design') || lower.includes('architect') || lower.includes('want a')) {
            // Dream Catcher Logic
            await this.generateDreamArchitecture(input);
        } else {
            vscode.window.showInformationMessage(`System heard: "${input}". Sending to Agent...`);
        }
    }

    async generateDreamArchitecture(idea) {
        const folders = vscode.workspace.workspaceFolders;
        if (!folders) return;

        const root = folders[0].uri.fsPath;
        vscode.window.showInformationMessage(`🧠 Dream Catcher: Designing architecture for "${idea}"...`);

        // Simulate thinking delay
        await new Promise(r => setTimeout(r, 2000));

        // 1. Create Implementation Plan
        const planPath = vscode.Uri.file(`${root}/implementation_plan.md`);
        const planContent = `# Project Architecture: ${idea}
## Overview
Generated by Codeoba Dream Catcher.

## Tech Stack
- Frontend: React / Next.js
- Backend: Node.js Express
- Database: PostgreSQL

## Core Features
1. User Authentication
2. Main Dashboard
3. Settings

## Database Schema
- Users (id, email, password_hash)
- Items (id, name, created_at)
`;
        await vscode.workspace.fs.writeFile(planPath, Buffer.from(planContent));

        // 2. Populate Task.md
        const taskPath = vscode.Uri.file(`${root}/task.md`);
        const taskContent = `- [ ] Setup Project
  - [ ] Initialize repositoryFrom Dream Catcher
  - [ ] Setup Database
  - [ ] Configure Auth
`;
        await vscode.workspace.fs.writeFile(taskPath, Buffer.from(taskContent));

        // 3. Create Folder Structure
        const dirs = ['src/api', 'src/ui', 'src/db', 'docs'];
        for (const dir of dirs) {
            await vscode.workspace.fs.createDirectory(vscode.Uri.file(`${root}/${dir}`));
        }

        vscode.window.showInformationMessage(`🧠 Architecture ready! Checked implementation_plan.md`);
        const doc = await vscode.workspace.openTextDocument(planPath);
        vscode.window.showTextDocument(doc);
    }
}
exports.VoiceCommander = VoiceCommander;
